preset: psr2

enabled:
  - concat_without_spaces
  - duplicate_semicolon
  - empty_return
  - extra_empty_lines
  - list_commas
  - multiline_array_trailing_comma
  - newline_after_open_tag
  - no_useless_else
  - ordered_use
  - php_unit_construct
  - php_unit_strict
  - return
  - short_array_syntax
  - single_array_no_trailing_comma
  - unalign_double_arrow
  - unalign_equals
  - unused_use
